<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) : ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) : ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
                    <div id="qty-counter" class="control" data-bind="scope: 'qty-counter'">
                        <!-- ko template: getTemplate() --><!-- /ko -->
                        <script type="text/x-magento-init">
                            {
                                "#qty-counter": {
                                    "Magento_Ui/js/core/app": {
                                        "components": {
                                            "qty-counter": {
                                                "component": "qty-counter",
                                                "config": {
                                                    "qty": <?php echo $block->getProductDefaultQty() * 1 ?>,
                                                    "dataValidate": <?php echo json_encode($block->getQuantityValidators()) ?>
                                                }
                                            }
                                         }
                                    }
                                }
                            }
                        </script>
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= $block->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }

</script>
